"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = "$username$hostname$directory$git_branch$git_status$python$nodejs$cmd_duration$line_break$character"

[directory]
truncation_length = 4
truncate_to_repo = false

[git_branch]
symbol = " "

[git_status]
disabled = false

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
